[lint]
# Enable the copyright rule
preview = true
extend-select = ["CPY"]

[extend-per-file-ignores]
"dysql/version.py" = ["CPY"]

[lint.flake8-copyright]
min-file-size = 200
notice-rgx = """\
\"\"\"
Copyright [(2)\\d{3}]* Adobe
All Rights Reserved.

NOTICE: Adobe permits you to use, modify, and distribute this file in accordance
with the terms of the Adobe license agreement accompanying it.
\"\"\"
"""
